### ISSUE TITLE
Could we get a seniority level for each challenge?

### ISSUE THREAD

**Issue by rpedrodasilva10** [CollabCodeTech/backend-challenges#37]
Hey @joviane!
First of all, thank you for creating this project, I think this is a good way to give someone a roadmap or things to build when they're bored.

What do you think about creating a column to show the challenge's seniority level?

ex: Challenge A -> Junior Level
Challenge B -> Mid/Senior 

Maybe contributors that already made the challenges could help us rank them.

**Comment by joviane** [comment]
Hi!

I like the idea to have a seniority level but most of the tests are applied independently of the level. The difference will be on the code review, on what the company expects.
