### ISSUE TITLE
como posso ajudar aqui?

### ISSUE THREAD

**Issue by ghost** [CollabCodeTech/backend-challenges#53]

**Comment by filhodanuvem** [comment]
fala @lucasnuic , uma forma de ajudar é abrindo um pull request com algum link público de um desafio técnico de backend para empresas do Brasil ou de fora seguindo o padrão de links que temos no README.md.

**Comment by filhodanuvem** [comment]
@lucasnuic não sou mantenedor do repo não. Você ta procurando oportunidade de criar uma primeira pull request?
